# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0, 0, 0]
simBoxHigh: [1000, 1000, 1.0]
simBoxPBC: [true, true, false]
monolayer: true
# initialization box
initBoxLow: [500, 500, 0]
initBoxHigh: [510, 510, 1]
initCircularX: false
# components outside [-1,1] will be randomly set
initOrient: [1, 0, 0]
# physical settings
viscosity: 0.0001 #pN/(um^2.s)
KBT: -0.00411 #pN.um, 300K
linkKappa: 0 # pN/um spring constant for sylinder links.
attKappa: 0 #pN. Attraction strength
attCutoff: 0.2 #um. Attraciton cutoff
# Sylinder
sylinderFixed: false
sylinderNumber: 1
sylinderLength: 3
sylinderLengthColRatio: 1.0
sylinderLengthSigma: -1.0 # <0 means no randomness
sylinderDiameter: 1.0
sylinderDiameterColRatio: 1.0
sylinderColBuf: 1.0
# time-stepping
dt: 0.0001 # s
timeTotal: 20 # s
timeSnap: 0.1 # s
# ConstraintSolver
conResTol: 1e-5 # residual
conMaxIte: 10000 # max iteration
conSolverChoice: 0 # 0 for BBPGD, 1 for APGD, etc
# growth settings
cellGrowth:
  - group: 0
    tauD: 1.0 # s
    Delta: 4.0 # um
    sigma: 0.0 # s
    angle: 0.1 # deg

