# program settings
# Brownian spheres at vol%=32.9673% for EOS verification
# theoretical P_collision = 8.2
rngSeed: 1234
# simulation box
simBoxLow: [0, 0, 0]
simBoxHigh: [10, 10, 10]
simBoxPBC: [true, true, true]
monolayer: false
# initialization box
initBoxLow: [0, 0, 0]
initBoxHigh: [10, 10, 10]
initCircularX: false
# components outside [-1,1] will be randomly set
initOrient: [2, 2, 2]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: -0.00411 #pN.um, 300K
linkKappa: 1000.0 # pN/um spring constant for sylinder links.
linkGap: 0.05 # um separation for sylinder links.
# Sylinder
sylinderFixed: false
sylinderNumber: 2000
sylinderLength: 1.0
sylinderLengthColRatio: 1.0
sylinderLengthSigma: -1.0 # <0 means no randomness
sylinderDiameter: 0.25
sylinderDiameterColRatio: 1.0
sylinderColBuf: 1.0
# time-stepping
dt: 0.0001 # s
timeTotal: 1.0 # s
timeSnap: 0.0001 # s
# ConstraintSolver
conResTol: 1e-5 # residual
conMaxIte: 10000 # max iteration
conSolverChoice: 1 # 0 for BBPGD, 1 for APGD, etc
initPreSteps: 0

