#!/bin/bash

TRILINOS_PATH=../Trilinos-trilinos-release-13-0-1

EXTRA_ARGS=$@

rm -f CMakeCache.txt

cmake \
    -D CMAKE_INSTALL_PREFIX:FILEPATH="$SFTPATH" \
    -D CMAKE_INSTALL_LIBDIR=lib \
    -D CMAKE_BUILD_TYPE:STRING="Release" \
    -D CMAKE_CXX_FLAGS:STRING="$CXXFLAGS" \
    -D CMAKE_C_FLAGS:STRING="$CFLAGS" \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_ENABLE_MKL:BOOL=ON \
    -D TPL_ENABLE_BLAS:BOOL=ON \
    -D TPL_ENABLE_LAPACK:BOOL=ON \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
    -D Trilinos_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_Fortran:BOOL=OFF \
    -D Trilinos_ENABLE_OpenMP:BOOL=ON \
    -D Trilinos_ENABLE_CXX11:BOOL=ON \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D Trilinos_ENABLE_Thyra:BOOL=ON \
    -D Tpetra_INST_SERIAL:BOOL=ON \
    -D Tpetra_INST_INT_INT:BOOL=ON \
    -D BUILD_SHARED_LIBS:BOOL=OFF \
    -D MPI_BASE_DIR:FILEPATH="$INTEL_MPI_ROOT" \
    -D MKL_INCLUDE_DIRS:STRING="$MKL_INCLUDE_DIRS" \
    -D MKL_LIBRARY_DIRS:FILEPATH="$MKL_LIB_DIRS" \
    -D MKL_LIBRARY_NAMES:STRING="mkl_rt" \
    -D BLAS_LIBRARY_DIRS:FILEPATH="$MKL_LIB_DIRS" \
    -D BLAS_LIBRARY_NAMES:STRING="mkl_rt" \
    -D LAPACK_LIBRARY_DIRS:FILEPATH="$MKL_LIB_DIRS" \
    -D LAPACK_LIBRARY_NAMES:STRING="mkl_rt" \
    $EXTRA_ARGS \
    $TRILINOS_PATH

