# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0, 0, 0]
simBoxHigh: [1000, 1000, 1.0]
simBoxPBC: [true, true, false]
monolayer: true
# initialization box
initBoxLow: [500, 500, 0]
initBoxHigh: [510, 510, 1]
initCircularX: false
# components outside [-1,1] will be randomly set
initOrient: [1, 0, 0]
# physical settings
viscosity: 0.0001 #pN/(um^2.s)
KBT: 0.00411 #pN.um, 300K
linkKappa: 0 # pN/um spring constant for particle links.
attKappa: 0 #pN. Attraction strength
attCutoff: 0.2 #um. Attraciton cutoff
# Particle
particleFixed: false
particleNumber: 1
particleLength: 3
particleLengthColRatio: 1.0
particleLengthSigma: -1.0 # <0 means no randomness
particleDiameter: 1.0
particleDiameterColRatio: 1.0
particleColBuf: 1.0
# time-stepping
dt: 0.0001 # s
timeTotal: 20 # s
timeSnap: 0.0001 # s
# ConstraintSolver
conResTol: 1e-4 # residual
conMaxIte: 100000 # max iteration
conSolverChoice: 0 # 0 for BBPGD, 1 for APGD, etc
