# program settings
rngSeed: 1234
# simulation box
simBoxLow: [0, 0, 0]
simBoxHigh: [40, 20, 20]
simBoxPBC: [false, True, True]
monolayer: false
# initialization box
initBoxLow: [0, 0, 0]
initBoxHigh: [40, 20, 20]
initCircularX: false
# components outside [-1,1] will be randomly set
initOrient: [2, 2, 2]
# physical settings
viscosity: 0.01 #pN/(um^2.s)
KBT: 0.00411 #pN.um, 300K
linkKappa: 1000.0 # pN/um spring constant for sylinder links.
linkGap: 0.01 # um separation for sylinder links.
# Sylinder
sylinderFixed: false
sylinderNumber: 400
sylinderLength: 3.0
sylinderLengthColRatio: 1.0
sylinderLengthSigma: -1.0 # <0 means no randomness
sylinderDiameter: 1.0
sylinderDiameterColRatio: 1.0
sylinderColBuf: 0.3
# time-stepping
dt: 0.00001 # s
timeTotal: 0.01 # s
timeSnap: 0.00001 # s
# ConstraintSolver
conResTol: 1e-5 # residual
conMaxIte: 100000 # max iteration
conSolverChoice: 0 # 0 for BBPGD, 1 for APGD, etc
# Boundaries
# boundaries:
#   - type: "sphere"
#     center: [15, 10, 10]
#     radius: 15
#     inside: true
